JuliePro/Controllers/CertificationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using JuliePro_DataAccess;
using JuliePro_DataModels;
using Microsoft.Extensions.Localization;
using JuliePro.Services;

namespace JuliePro.Controllers
{
    public class CertificationController : Controller
    {
        private readonly ICertificationService _service;
        private readonly IStringLocalizer<CertificationController> _localizer;

        public CertificationController(ICertificationService service, IStringLocalizer<CertificationController> localizer)
        {
            _service = service;
            _localizer = localizer;
        }

        // GET: Certification
        public async Task<IActionResult> Index()
        {
            return View(await _service.GetAllAsync());
                        
        }

        public async Task<IActionResult> TrainerIndex(int trainerId) {

            return View(await _service.GetAllByTrainerAsync(trainerId));
        
        }

        // GET: Certification/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null )
            {
                return NotFound();
            }

            var certification = await _service.GetByIdAsync(id.Value);

            if (certification == null)
            {
                return NotFound();
            }

            return View(certification);
        }

        // GET: Certification/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Certification/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Certification certification)
        {
            ModelState.Remove(nameof(certification.TrainerCertification));

            if (ModelState.IsValid)
            {
                await _service.CreateAsync(certification);
                return RedirectToAction(nameof(Index));
            }
            return View(certification);
        }

        // GET: Certification/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var certification = await _service.GetByIdAsync(id.Value);
            if (certification == null)
            {
                return NotFound();
            }
            return View(certification);
        }

        // POST: Certification/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, Certification certification)
        {

            ModelState.Remove(nameof(certification.TrainerCertification));

            if (id != certification.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                  await _service.EditAsync(certification);
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!(await _service.ExistsAsync(id)))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(certification);
        }

        // GET: Certification/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null )
            {
                return NotFound();
            }

            var certification = await _service.GetByIdAsync(id.Value);
            if (certification == null)
            {
                return NotFound();
            }

            return View(certification);
        }

        // POST: Certification/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
          
            await _service.DeleteAsync(id);
            
           
            return RedirectToAction(nameof(Index));
        }

        
    }
}

JuliePro/Controllers/DisciplineController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using JuliePro_DataAccess;
using JuliePro_DataModels;
using JuliePro.Services;

namespace JuliePro.Controllers
{
    public class DisciplineController : Controller
    {
        private readonly IServiceBaseAsync<Discipline> _service;

        public DisciplineController(IServiceBaseAsync<Discipline> service)
        {
            _service = service;
        }

        // GET: Discipline
        public async Task<IActionResult> Index()
        {
            return View(await  _service.GetAllAsync());
        }

        // GET: Discipline/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var discipline = await _service.GetByIdAsync(id.Value);
            if (discipline == null)
            {
                return NotFound();
            }

            return View(discipline);
        }

        // GET: Discipline/Create
        public async Task<IActionResult> Create()
        {
            ViewData["Parent_Id"] = new SelectList((await _service.GetAllAsync()), "Id", "Description");
            return View();
        }

        // POST: Discipline/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Discipline discipline)
        {
            ModelState.Remove(nameof(discipline.Parent));
            if (ModelState.IsValid)
            {
               await _service.CreateAsync(discipline);
                return RedirectToAction(nameof(Index));
            }
            ViewData["Parent_Id"] = new SelectList((await _service.GetAllAsync()), "Id", "Name", discipline.Parent_Id);
            return View(discipline);
        }

        // GET: Discipline/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var discipline = await _service.GetByIdAsync(id.Value);
            if (discipline == null)
            {
                return NotFound();
            }
            ViewData["Parent_Id"] = new SelectList((await _service.GetAllAsync()), "Id", "Name", discipline.Parent_Id);
            return View(discipline);
        }

        // POST: Discipline/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, Discipline discipline)
        {

            ModelState.Remove(nameof(discipline.Parent));
            if (id != discipline.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    await _service.EditAsync(discipline);
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!(await _service.ExistsAsync(discipline.Id)))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["Parent_Id"] = new SelectList((await _service.GetAllAsync()), "Id", "Name", discipline.Parent_Id);
            return View(discipline);
        }

        // GET: Discipline/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var discipline = await _service.GetByIdAsync(id.Value);

            if (discipline == null)
            {
                return NotFound();
            }

            return View(discipline);
        }

        // POST: Discipline/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
           
           await _service.DeleteAsync(id);
            
           return RedirectToAction(nameof(Index));
        }

      
    }
}

JuliePro/Controllers/TrainerCertificationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using JuliePro_DataAccess;
using JuliePro_DataModels;
using JuliePro.Services;

namespace JuliePro.Controllers
{
    public class TrainerCertificationController : Controller
    {
        private readonly IServiceBaseAsync<TrainerCertification> _service;
        private readonly IServiceBaseAsync<Certification> _certificationService;
        private ITrainerService _trainerService;

        public TrainerCertificationController(IServiceBaseAsync<TrainerCertification> service, IServiceBaseAsync<Certification> certificationService, ITrainerService trainerService)
        {
            _service = service;
            _certificationService = certificationService;
            _trainerService = trainerService;

        
        }

        // GET: TrainerCertification
        public async Task<IActionResult> Index()
        {
        
            return View(await _service.GetAllAsync());
        }

        // GET: TrainerCertification/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var trainerCertification = await _service.GetByIdAsync(id.Value);
            if (trainerCertification == null)
            {
                return NotFound();
            }

            return View(trainerCertification);
        }

        // GET: TrainerCertification/Create
        public async Task<IActionResult> Create(int? certificationId, int? trainerId)
        {

            var model = new TrainerCertification() { Certification_Id = certificationId ?? 0, Trainer_Id = trainerId ?? 0}; 


            ViewData["Certification_Id"] = new SelectList(await _certificationService.GetAllAsync(), "Id", "FullTitle");
            ViewData["Trainer_Id"] = new SelectList(await _trainerService.GetAllAsync() , "Id", "FullName");
            return View(model);
        }

        // POST: TrainerCertification/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create( TrainerCertification trainerCertification)
        {
            ModelState.Remove(nameof(trainerCertification.Trainer));
            ModelState.Remove(nameof(trainerCertification.Certification));
            if (ModelState.IsValid)
            {
                await _service.CreateAsync(trainerCertification);
                return RedirectToAction(nameof(Index));
            }
            ViewData["Certification_Id"] = new SelectList(await _certificationService.GetAllAsync(), "Id", "FullTitle");
            ViewData["Trainer_Id"] = new SelectList(await _trainerService.GetAllAsync(), "Id", "FullName");
            return View(trainerCertification);
        }

        // GET: TrainerCertification/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var trainerCertification = await _service.GetByIdAsync(id.Value);
            if (trainerCertification == null)
            {
                return NotFound();
            }
            ViewData["Certification_Id"] = new SelectList(await _certificationService.GetAllAsync(), "Id", "FullTitle");
            ViewData["Trainer_Id"] = new SelectList(await _trainerService.GetAllAsync(), "Id", "FullName");
            return View(trainerCertification);
        }

        // POST: TrainerCertification/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, TrainerCertification trainerCertification)
        {

            ModelState.Remove(nameof(trainerCertification.Trainer));
            ModelState.Remove(nameof(trainerCertification.Certification));

            if (id != trainerCertification.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    await _service.EditAsync(trainerCertification);
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!await _service.ExistsAsync(trainerCertification.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["Certification_Id"] = new SelectList(await _certificationService.GetAllAsync(), "Id", "FullTitle");
            ViewData["Trainer_Id"] = new SelectList(await _trainerService.GetAllAsync(), "Id", "FullName");
            return View(trainerCertification);
        }

        // GET: TrainerCertification/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null )
            {
                return NotFound();
            }

            var trainerCertification = await _service.GetByIdAsync(id.Value);
            if (trainerCertification == null)
            {
                return NotFound();
            }

            return View(trainerCertification);
        }

        // POST: TrainerCertification/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            await _service.DeleteAsync(id);
            return RedirectToAction(nameof(Index));
        }

    }
}

JuliePro/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - JuliePro</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/JuliePro.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.0/css/all.min.css" integrity="sha512-xh6O/CkQoPOWDdYTDqeRdPCVd1SpvCA9XXcUnZS2FmJNp1coAFzvtCN9BmamE+4aHK8yyUHUSCcJHgXloTyT2A==" crossorigin="anonymous" referrerpolicy="no-referrer" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light border-bottom box-shadow mb-3" style="background-image: url('/images/banner.jpg'); background-size:cover; background-position:center; ">
            <div class="container-fluid" style="align-items: baseline;">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"><object data="~/images/haltere.svg" type="image/svg+xml" ></object></a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">@Locals["Home"]</a>
                        </li>
            <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDarkDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            @Locals["Manage"] ▼
          </a>
          <ul class="dropdown-menu dropdown-menu-dark" aria-labelledby="navbarDarkDropdownMenuLink">
            <li><a class="dropdown-item" asp-action="Index" asp-controller="Certification">@Locals["Certification"]</a></li>
            <li><a class="dropdown-item" asp-action="Index" asp-controller="Discipline">@Locals["Discipline"]</a></li>
            <li><a class="dropdown-item" asp-action="Index" asp-controller="Record">@Locals["Record"]</a></li>
            <li><a class="dropdown-item" asp-action="Index" asp-controller="TrainerCertification">@Locals["TrainerCertification"]</a></li>
            <li><a class="dropdown-item" asp-action="Index" asp-controller="Trainer">@Locals["Trainer"]</a></li>
           </ul>
        </li>
                    </ul>
                     <div class="text-right">
                        @* TODO : Mettre le commutateur de langue *@
                        @await Html.PartialAsync("_SelectLanguage");

                    </div>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted bg-white" style="position:fixed;bottom:0;">
        <div class="container">
            &copy; 2022 - JuliePro
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

JuliePro/Views/Shared/_SelectLanguage.cshtml
@using Microsoft.AspNetCore.Builder
@using Microsoft.AspNetCore.Mvc.Localization
@using Microsoft.Extensions.Options
@inject IOptions<RequestLocalizationOptions> LocOptions
@{
  var requestCulture = Context.Features.Get<Microsoft.AspNetCore.Localization.IRequestCultureFeature>();
  var cultureItems = LocOptions.Value.SupportedUICultures
      .Select(c => new SelectListItem { Value = c.Name, Text = c.NativeName })
      .ToList();
}
<div style="display: inline-block; vertical-align: middle;">
  <form id="selectLanguage" asp-controller="Home"
        asp-action="SetLanguage" asp-route-returnUrl="@Context.Request.Path"
        method="post" class="form-horizontal" role="form">
    <div class="form-group" style="margin-bottom:0">
      <select onchange="this.form.submit()" name="culture" class="form-control btn btn-primary"
              asp-for="@requestCulture.RequestCulture.UICulture.Name" asp-items="cultureItems">
      </select>
    </div>
  </form>
</div>